### ISSUE TITLE
a test script might help some users

### ISSUE THREAD

**Issue by UnixJunkie** [UnixJunkie/FASMIFRA#15]
although there are commands in the README.md already...

**Comment by UnixJunkie** [comment]
@matthewcarbone you can have a look at test.sh maybe.

**Comment by matthewcarbone** [comment]
@UnixJunkie this script is broken as there is no `_build/default/src/fasmifra.exe` file generated during the Make process.

**Comment by UnixJunkie** [comment]
If it was broken, do you honestly think I would have put and committed this script into this public repository?

**Comment by matthewcarbone** [comment]
@UnixJunkie can you show me where in the make process that the file `fasmifra.exe` is generated? It doesn't appear to be created for me.

> If it was broken, do you honestly think I would have put and committed this script into this public repository?

Please do not take any of this personally. Codes have bugs, and users have misunderstandings about how the code works. One of those two things is going on here, and neither is a big deal. 👍

**Comment by UnixJunkie** [comment]
If you have installed dune properly (it should be installed by opam)
you can force the build of the exe like this in a source checkout of FASMIFRA:
```bash
dune build src/fasmifra.exe
```
