### ISSUE TITLE
_build/default/src/fasmifra.exe: No such file or directory'

### ISSUE THREAD

**Issue by wangyingyu1993** [UnixJunkie/FASMIFRA#19]
"When I run './fasmifra -n 100000 -i my_molecules_frags.smi -o my_molecules_gen.smi' on Ubuntu, it shows './fasmifra: line 1: _build/default/src/fasmifra.exe: No such file or directory'."

**Comment by UnixJunkie** [comment]
try the command make before

**Comment by UnixJunkie** [comment]
maybe better, execute the ./install.sh script in your git checkout of the sources; it should build and install everything

**Comment by UnixJunkie** [comment]
Do you still have any problem?

**Comment by wangyingyu1993** [comment]
Thank you very much, the process of generating molecules has been implemented. I directly copied the executable file pointed to in the fasmifra directory to the local folder and named it fasmifra_1. However, there remains an issue: when I run './fasmifra_1 -i my_molecules_frags.smi -o my_molecules_gen.smi -n 100000 --seed 1 --deep-smiles', the majority of the 100,000 generated complete molecules contain abnormal atoms, as shown in the figure
![picture](https://github.com/user-attachments/assets/7aee2d9c-be88-4c73-96e3-313f5c65c794)

**Comment by UnixJunkie** [comment]
Ok, what you call abnormal atoms are supposed to only appear in fragmented molecules.
In generated molecules, they should not show up.

Try the ./install.sh script first, to create a proper installation of FASMIFRA from scratch.

Once this is done, execute the ./test.sh script.

Then, look at the molecules created in gen_1k.smi.
If they are OK, then the software was installed and runs correctly.

**Comment by wangyingyu1993** [comment]
Generating error SMILES, could you please help me find the cause?
![picture](https://github.com/user-attachments/assets/e43f8fae-595a-4ad8-a385-ef7f24c73c95)

**Comment by UnixJunkie** [comment]
Are you inside a docker container or something?
I almost never use docker, someone had the same problem than you in the past, and was also a docker user.

**Comment by UnixJunkie** [comment]
Maybe have a look in there https://github.com/UnixJunkie/FASMIFRA/issues/16

**Comment by UnixJunkie** [comment]
I updated test.sh, can you try running it again?

Copy-paste the whole text output if it doesn't work.

**Comment by UnixJunkie** [comment]
If opam managed to install fasmifra (what the ./install.sh script does).
Then executing
```bash
eval `opam config env`
```
in your shell should make fasmifra_fragment.py and fasmifra (the ocaml executable), available in your PATH.
Then, you should be able to fragment any SMILES file and generate molecules from the obtained fragments.

**Comment by wangyingyu1993** [comment]
The issue has been resolved. In the `test.sh` script, I modified the line `bin/fasmifra_fragment.py -i all_data.smi -o all_data_frags.smi` to `/home/wyy/.opam/default/bin/fasmifra_fragment.py -i all_data.smi -o all_data_frags.smi`, and that did the trick. Many thanks for the assistance!

**Comment by wangyingyu1993** [comment]
The issue has been resolved. In the `test.sh` script, I modified the line `bin/fasmifra_fragment.py -i chembl_1k.smi -o chembl_1k_frags.smi` to `/home/wyy/.opam/default/bin/fasmifra_fragment.py -i all_data.smi -o all_data_frags.smi`, and that did the trick. Many thanks for the assistance!

**Comment by wangyingyu1993** [comment]
The issue has been resolved. In the `test.sh` script, I modified the line `bin/fasmifra_fragment.py -i chembl_1k.smi -o chembl_1k_frags.smi` to `/home/wyy/.opam/default/bin/fasmifra_fragment.py -i chembl_1k.smi -o chembl_1k_frags.smi`, and that did the trick. Many thanks for the assistance!

**Comment by UnixJunkie** [comment]
Ok, perfect!
I hope you will cite our manuscript if FASMIFRA is useful to you.
