### ISSUE TITLE
The format of my_molecules.smi

### ISSUE THREAD

**Issue by wangyingyu1993** [UnixJunkie/FASMIFRA#20]
Does my_molecules.smi require two columns of data, with the first column being the full SMILES strings and the second column intended for what content exactly? I have filled the second column with indices directly—would this be appropriate?

**Comment by UnixJunkie** [comment]
Yes, apparently I require that a proper SMILES line is:
SMILES\tMOL_NAME\n

**Comment by UnixJunkie** [comment]
If you name your molecules using integers, as you are proposing, it should work.
That's not a very good molecular naming scheme, but why not.

**Comment by UnixJunkie** [comment]
In ./test.sh, you see compilation (make) then some usage example.
So, this repository even includes some sample data that is known to work and that you can check for format, etc.

**Comment by UnixJunkie** [comment]
Once everything is working fine, let me know and I will close your issues.

**Comment by wangyingyu1993** [comment]
Okay, I'll try it right away.
