### ISSUE TITLE
Kekulization during fragmentation [question]

### ISSUE THREAD

**Issue by PatWoo23** [UnixJunkie/FASMIFRA#25]
Hi! May I seek your advice on how the codes solve the kekulization issue with generating fragments?

**Comment by UnixJunkie** [comment]
In the paper, look for extended bond typing.

We don't link fragments randomly: only "compatible" fragments can be linked
together.

Also, we only cut single bonds out of rings.

**Comment by UnixJunkie** [comment]
https://doi.org/10.1186/s13321-021-00566-4

**Comment by PatWoo23** [comment]
Thank you for your help! Issue resolves after using lig = next(Chem.SDMolSupplier(sdf, sanitize=False)). Thank you for your great work! The neural network is very sophisticated!
