### ISSUE TITLE
Simple Use Case Illustration?

### ISSUE THREAD

**Issue by eahenle** [UnixJunkie/FASMIFRA#7]
I would like to use this code to generate a synthetic data set by combining a limited set of simple fragments into molecules, but I am having trouble obtaining the expected results.  To test my approach, I took your TCM_20k dataset and did the following:

`fasmifra_fragment.py -i TCM_20k.smi -o fragments.smi
fasmifra -i fragments.smi -o molecules.smi -n 6000`

There are 16k unique molecules in the input data set; these are processed into 20k fragments; and the end result is 6k unique outputs.  So, the approach seems correct.

However, trying this with a set of small molecules is not successful.  With 6 unique inputs, only 6 fragments are generated, and from those only 6 molecules are built (and each is simply a copy of one original input).  This is the result regardless of the value chosen for the `-w` option during fragmentation.  Clearly, there is something about my data set that does not work with one or the other part of the pipeline.

It would be helpful to have some documentation on input data format requirements, basic use examples, and a thorough description (with example) of how manually-created fragments can be used.

**Comment by UnixJunkie** [comment]
Have you read the article?

**Comment by UnixJunkie** [comment]
fasmifra_fragment.py has a -n option that might be useful in your case.
```bash
usage: fasmifra_fragment.py [-h] [-i input.smi] [-o output.smi] [--seed SEED]
                            [-n NB_PASSES] [-w FRAG_WEIGHT]

fragment molecules (tag cut bonds)

optional arguments:
  -h, --help      show this help message and exit
  -i input.smi    molecules input file
  -o output.smi   fragments output file
  --seed SEED     RNG seed
  -n NB_PASSES    number of fragmentation passes
  -w FRAG_WEIGHT  fragment weight (default=150Da)
```
i.e. despite you have very few molecules, try to get more fragments out of them.
In addition, if your input molecules have very few single bonds out of rings and not involved in stereo chemistry, the fragmentation approach we use might not be applicable in your case.

**Comment by UnixJunkie** [comment]
README.md has an example use case.
